### ISSUE TITLE
Field guide section on W UMa binaries

### ISSUE THREAD

**Issue by janvanroestel** [ZwickyTransientFacility/scope#7]
A field guide entry of WUMa binaries is needed

**Feature Summary**
write a description, show an example light curve, and add the golden set for WUMa binaries

**Usage / behavior**
similar to RRLyr page

**Implementation details**
See https://scope.ztf.dev/developer.html#contributing-field-guide-sections

**Comment by dmitryduev** [comment]
@janvanroestel please refer folks to https://scope.ztf.dev/developer.html#contributing-field-guide-sections.

**Comment by janvanroestel** [comment]
For some reason, the trimming of trailing whitespaces fails, any suggestions?

![image](https://user-images.githubusercontent.com/10774087/111717618-a3e02a80-8815-11eb-9fcf-6531fd17de70.png)

**Comment by dmitryduev** [comment]
@janvanroestel please pull in `main`, there was a typo in `black`'s settings that I just fixed.

**Comment by mcoughlin** [comment]
For reference, the Zooniverse version has:

## [attached eclipsing binary](https://en.wikipedia.org/wiki/W_Ursae_Majoris_variable) (W UMa)
 - Range of amplitudes (~0.1 to ~0.8 mag)
 - Intermediate periods (log Period between -1 and 0)
 - almost sinusoidal light curves (if you "flip" them across the horizontal access they are not quite symmetric)

Attached eclipsing binaries (also called [W UMa variables](https://en.wikipedia.org/wiki/W_Ursae_Majoris_variable)) are binary star systems (i.e. two stars that are in orbit around each other) that are aligned such that they eclipse each other relative to our line of sight from the Earth. They are considered "attached" because they are so close that these is mass being transferred back and forth between the two stars. For this reason there is never a moment where all the light from both stars can be seen, essentially one of the two stars is always eclipsing part of the other.

Any type of star can be in an eclipsing binary (so they may be small, large, hot, cool, etc.), which in turn can lead to a large range in eclipse amplitudes (though typically these are between 0.1 and 0.8 mag, with most in the ~0.3 to 0.7 mag range) or eclipse periods (though our observations are typically only sensitive to periods between 0.1 to a few days for attached EBs).

**Comment by janvanroestel** [comment]
For some reason, the 'lint' check keeps failing on "Kowalski not available" not sure what is going on here
